server:
  port: 3344

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      name: hello,this is spring cloud config repository, master branch's config-dev.yml file contents
